### ISSUE TITLE
您好，我在运行webshop环境的时候遇到了一些问题

### ISSUE THREAD

**Issue by xiaxiaxiatengxi** [YifeiZhou02/ArCHer#3]
![image](https://github.com/YifeiZhou02/ArCHer/assets/64694898/bf7ac117-ee11-4c59-9682-e1b7e03a786a)
您好，我启动了webshop环境如图
ip是127.0.0.1:3000

之后我启动archer
python run.py --config-name archer_webshop

但我还是报错……无法链接
![image](https://github.com/YifeiZhou02/ArCHer/assets/64694898/e09b5ac9-6fde-4d2c-ad1d-4c02ed1909b9)

**Comment by YifeiZhou02** [comment]
Hi,

Could you provide the complete traceback for the error? There could be several reasons to it:

- Make sure to launch the webshop in the same node/machine so that the python script can access it.
- Sometimes webshop server can take a very long time to start (more than 20 minutes), it could be the case that webshop is still starting.

For debugging, you can manually open the webshop link in a browser and try searching something to see if there are results popping up. It could also be the webshop environment has not been successfully set ip.

**Comment by xiaxiaxiatengxi** [comment]
嗨，谢谢。已解决，谢谢！！
